[package]
name = "nanocount"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
binseq = "0.8.3"
clap = { version = "4.5.54", features = ["derive"] }
csv = "1.4.0"
parking_lot = "0.12.5"
sassy = "0.1.10"
serde = { version = "1.0.228", features = ["derive"] }
